apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log-namespace
  name: dwk-logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-logoutput
  template:
    metadata:
      labels:
        app: dwk-logoutput
    spec:
    spec:
      volumes:
        - name: shared-logoutput
          emptyDir: {}
        - name: log-config
          configMap:
            name: log-config
      containers:
        - name: dwk-logoutput-writer
          image: roaringduck/dwk-logoutput-writer
          volumeMounts:
          - name: shared-logoutput
            mountPath: /usr/src/app/files
          - name: log-config
            mountPath: /usr/src/app/config
        - name: dwk-logoutput-reader
          image: roaringduck/dwk-logoutput-reader
          volumeMounts:
          - name: shared-logoutput
            mountPath: /usr/src/app/files
          - name: log-config
            mountPath: /usr/src/app/config
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-config
                  key: MESSAGE