apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets/postgres-conf.yaml
  - manifests/config.yaml
  - manifests/postgres.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/deployment.yaml
images:
  - name: IMAGE
    newName: roaringduck/dwk-pingpongapp:ex407