apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secrets/postgres-conf.yaml
- manifests/config.yaml
- manifests/postgres.yaml
- manifests/knative-service.yaml
images:
- name: IMAGE
  newName: roaringduck/dwk-pingpongapp
  newTag: 03a6b7ed6484b16ea82fca4c6e0a99d43b8614d4
