resources:
- ../../base
- postgres-backup.yaml
patches:
- path: config.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todoapp-prod
images:
- name: BACKEND-IMAGE
  newName: roaringduck/dwk-todoapp-backend
  newTag: 65b66504c56b42803cf5ddf4c3983766e97c0085
- name: BROADCASTER-IMAGE
  newName: roaringduck/dwk-todoapp-broadcaster
  newTag: 65b66504c56b42803cf5ddf4c3983766e97c0085
- name: FRONTEND-IMAGE
  newName: roaringduck/dwk-todoapp-frontend
  newTag: 65b66504c56b42803cf5ddf4c3983766e97c0085
