apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: log-namespace
  name: dwk-pingpongapp
spec:
  template:
    spec:
      containers:
        - image: IMAGE
          volumeMounts:
            - name: pingpongapp-volume
              mountPath: /usr/src/app/files
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pingpong-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: pingpongapp-config
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: pingpongapp-config
                  key: POSTGRES_USER
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /
              port: 8080
      volumes:
        - name: pingpongapp-volume
          emptyDir: {}
