apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikipedia-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikipedia-app
  template:
    metadata:
      labels:
        app: wikipedia-app
    spec:
      volumes:
        - name: shared-html
          emptyDir: {}
      initContainers:
        - name: init-kubernetes-page
          image: curlimages/curl
          command:
            - /bin/sh
            - "-c"
            - "curl -o /usr/share/nginx/html/index.html https://en.wikipedia.org/wiki/Kubernetes"
          volumeMounts:
            - name: shared-html
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: shared-html
              mountPath: /usr/share/nginx/html
        - name: sidecar-random-wiki
          image: curlimages/curl
          command:
            - /bin/sh
            - "-c"
            - |
              while true; do
                sleep $((300 + RANDOM % 600));
                curl -L -o /usr/share/nginx/html/index.html https://en.wikipedia.org/wiki/Special:Random;
              done
          volumeMounts:
            - name: shared-html
              mountPath: /usr/share/nginx/html
