apiVersion: v1
kind: Service
metadata:
  namespace: log-namespace
  name: dwk-logoutput-svc
spec:
  type: ClusterIP
  selector:
    app: dwk-logoutput
  ports:
    - port: 10001
      protocol: TCP
      targetPort: 9001