resources:
- ../../base
patches:
- path: config.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todoapp-staging
images:
- name: BACKEND-IMAGE
  newName: roaringduck/dwk-todoapp-backend
  newTag: e94554241fcc951cdcd38ea8d142bc52e7891619
- name: BROADCASTER-IMAGE
  newName: roaringduck/dwk-todoapp-broadcaster
  newTag: e94554241fcc951cdcd38ea8d142bc52e7891619
- name: FRONTEND-IMAGE
  newName: roaringduck/dwk-todoapp-frontend
  newTag: e94554241fcc951cdcd38ea8d142bc52e7891619
