resources:
- ../../base
namePrefix: staging-
patches:
- path: config.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todoapp-staging
images:
- name: BACKEND-IMAGE
  newName: roaringduck/dwk-todoapp-backend
  newTag: 1928e67fa066da0c6154f6b7724f33d5c853eb0b
- name: BROADCASTER-IMAGE
  newName: roaringduck/dwk-todoapp-broadcaster
  newTag: 1928e67fa066da0c6154f6b7724f33d5c853eb0b
- name: FRONTEND-IMAGE
  newName: roaringduck/dwk-todoapp-frontend
  newTag: 1928e67fa066da0c6154f6b7724f33d5c853eb0b
