apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - config.yaml
  - service.yaml
  - service-backend.yaml
  - ingress.yaml
  - persistentvolumeclaim.yaml
  - analysistemplate.yaml
  - rollout.yaml
  - hourly-article.yaml