apiVersion: v1
kind: ConfigMap
metadata:
  namespace: todo-namespace
  name: todoapp-config
data:
  POSTGRES_HOST: "postgres-todo-svc"
  POSTGRES_USER: "postgres"
  TODOS_DB: "todosdb"
  NATS_URL: "my-nats:4222"