apiVersion: v1
kind: Service
metadata:
  namespace: todo-namespace
  name: dwk-todoapp-svc
spec:
  type: ClusterIP
  selector:
    app: dwk-todoapp
  ports:
    - port: 10000
      protocol: TCP
      targetPort: 9000