name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE_FRONTEND: dwk-todoapp-frontend
  IMAGE_BACKEND: dwk-todoapp-backend
  SERVICE: dwk-todoapp-dep
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Build
        run: |-
          docker build ./TodoApp/TodoAppFrontend/ --tag "gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:$BRANCH-$GITHUB_SHA"
          docker build ./TodoApp/TodoAppBackend/ --tag "gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$BRANCH-$GITHUB_SHA"

      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:$BRANCH-$GITHUB_SHA"
          docker push "gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$BRANCH-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: SOPS decrypt
        run: |-
          curl -LO https://github.com/getsops/sops/releases/download/v3.9.0/sops-v3.9.0.linux.amd64
          mv sops-v3.9.0.linux.amd64 /usr/local/bin/sops
          chmod +x /usr/local/bin/sops
          export SOPS_AGE_KEY=${{ secrets.SOPS_KEY }}
          sops --decrypt TodoApp/secrets/postgres-conf.enc.yaml > TodoApp/secrets/postgres-conf.yaml

      - name: Deploy
        run: |-
          cd TodoApp
          kubectl create namespace ${GITHUB_REF#refs/heads/} || true
          kubectl config set-context --current --namespace=${GITHUB_REF#refs/heads/}
          kustomize edit set namespace ${GITHUB_REF#refs/heads/}
          kustomize edit set image FRONTEND-IMAGE=gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:$BRANCH-$GITHUB_SHA
          kustomize edit set image BACKEND-IMAGE=gcr.io/$PROJECT_ID/$IMAGE_BACKEND:$BRANCH-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $SERVICE -n todo-namespace
          kubectl get services -o wide